fastlane_version "1.101.0"

default_platform :ios

platform :ios do
  before_all do
    setup_mailgun
    git_pull(only_tags: true)
  end

  def get_podspec_version
    return %x(sh version_extractor.sh)
  end

  def bump_pod_version(oldVersion, newVersion)
    %x(perl -pi -e "s/#{oldVersion}/#{newVersion}/g" ../SwiftHelpSet.podspec)
  end

  def setup_mailgun
    ENV['MAILGUN_SANDBOX_POSTMASTER'] ||= "sandboxdcd43ccc257443bd929193174db3f0b7.mailgun.org"
    ENV['MAILGUN_APIKEY'] = "key-da2fb4d81808256057a325cec91392bc"
    ENV['MAILGUN_APP_LINK'] = "https://github.com/dalu93/SwiftHelpSet"
  end

  lane :release do |options|
    # ensure_git_status_clean

    test

    version_number = options[:version_number] || get_podspec_version
    bump_version_number = !!options[:version_number]

    if bump_version_number
      bump_pod_version(get_podspec_version, version_number)
    end

    %x(git add -A && git commit -a -m "Increment version to #{version_number}")

    push_to_git_remote

    add_git_tag(
      tag: version_number
    )
    push_git_tags

    # mailgun(
    #   to: "dalberti.luca93@gmail.com",
    #   success: true,
    #   message: "Successfully released version #{version_number} for SwiftHelpSet"
    # )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  error do |lane, exception|
    # mailgun(
    #   to: "dalberti.luca93@gmail.com",
    #   success: false,
    #   message: exception.message
    # )
  end
end
